services:
  db:
    container_name: auth_and_pay_services_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - 5432
    volumes:
      - auth_and_pay_services:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "-c", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 5
      timeout: 10s
    networks:
      - auth_and_pay_services

  app:
    container_name: auth_and_pay_services_app
    build: .
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c 'alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - auth_and_pay_services

volumes:
  auth_and_pay_services:

networks:
  auth_and_pay_services:
