"""init_migration

Revision ID: c297fbf78624
Revises: 
Create Date: 2025-05-06 18:21:12.954196

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import column, table

from routers.auth import bcrypt_context


# revision identifiers, used by Alembic.
revision: str = 'c297fbf78624'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    users_table = table(
        'users',
        column('email', sa.String),
        column('username', sa.String),
        column('first_name', sa.String),
        column('last_name', sa.String),
        column('password', sa.String),
        column('is_active', sa.Boolean),
        column('is_admin', sa.Boolean)
    )
    op.bulk_insert(users_table, [
        {
            'email': 'admin@example.com',
            'username': 'admin',
            'first_name': 'Admin',
            'last_name': 'Adminov',
            'password': bcrypt_context.hash('Admin123'),
            'is_active': True,
            'is_admin': True
        },
        {
            'email': 'user1@example.com',
            'username': 'user1',
            'first_name': 'User',
            'last_name': 'Userov',
            'password': bcrypt_context.hash('User123'),
            'is_active': True,
            'is_admin': False
        }
    ])

    op.create_table('accounts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('total', sa.Float(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)

    accounts_table = table(
        'accounts',
        column('total', sa.Integer),
        column('user_id', sa.Integer),
    )

    op.bulk_insert(accounts_table, [
        {
            'total': 0,
            'user_id': 1
        },
        {
            'total': 0,
            'user_id': 2
        }
    ])

    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('transaction_id', sa.String(), nullable=True),
                    sa.Column('account_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
